### ISSUE TITLE
Get Seeders In Response

### ISSUE THREAD

**Issue by Wamy-Dev** [iPromKnight/zilean#66]
It would be nice to get the number of seeders as that is usually a very important metric when choosing a torrent to download.

**Comment by iPromKnight** [comment]
Sorry - Not something Zilean will do.
Its purely for torrents that have been parsed previously by DMM
I dont want to have to become either a peer or join the DHt network in order to get seed information, and Zilean shouldn't be responsible for communication with the RD api. It should be the upstream app.

Cyphers Blackhole is probably where this should be implemented - However, the RD api call for instant availability does not return seeders and peers either
